{% set version = "1.0.0" %}

package:
    name: gridfill
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/ajdawson/gridfill/archive/v{{ version }}.tar.gz
    md5: 7258701d8296f974268e634ea09ed673

build:
    number: 0
    script:
        - python setup.py install --single-version-externally-managed --record record.txt  # [not (win and py<35)]
        - python setup.py build --compiler=mingw32  # [win and py<35]
        - python setup.py install  # [win and py<35]

requirements:
    build:
        - python
        - setuptools
        - cython
        - numpy x.x
        - mingwpy  # [win and py<35]
    run:
        - python
        - numpy x.x

test:
    requires:
        - nose
    imports:
        - gridfill

about:
    home: https://github.com/ajdawson/gridfill
    license: MIT
    summary: Fill missing values in a grid by solving Poisson's equation via an iterative relaxation scheme

extra:
    recipe-maintainers:
        - ajdawson
        - ocefpaf
