{% set version = "1.0.0" %}

package:
    name: gridfill
    version: {{ version }}

source:
    fn: v{{ version }}.tar.gz
    url: https://github.com/ajdawson/gridfill/archive/v{{ version }}.tar.gz
    md5: 7258701d8296f974268e634ea09ed673

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - cython
        - numpy x.x
    run:
        - python
        - numpy x.x

test:
    requires:
        - nose
    imports:
        - gridfill

about:
    home: https://github.com/ajdawson/gridfill
    license: MIT
    summary: Fill missing values in a grid by solving Poisson's equation via an iterative relaxation scheme

extra:
    recipe-maintainers:
        - ajdawson
        - ocefpaf
