# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_NPY=110  CONDA_PY=27
    - CONDA_NPY=111  CONDA_PY=27
    - CONDA_NPY=110  CONDA_PY=34
    - CONDA_NPY=111  CONDA_PY=34
    - CONDA_NPY=110  CONDA_PY=35
    - CONDA_NPY=111  CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NeaBhuE3oSaXQU216GZsi+zPs25g1+ydW7WhqPCj3u9nCsLTyfD51vF+0pQg0SsUfyHI7j/aoa/bnrN/xTQn7E+sKMUEQpucmGbPW82lhn2PhV65Q4tgLd4AiXgE92RVRd0TzR6oYZde/PLTcqsJDIm24UFSY/nNMGUjKjx9sJFw+YIDvuwlXywJtPynol4yBvpjhrkbSsoMh8LTJOw4EsB0ghXX/BQD7SR4CEicWJEsNZE4/DCFbxtKAi2DHVT+tUpE2Rsl09UOM6qmqPz86+nWEnhN2YfosFAMLeVmQEHCFtsRBcOr2fxLzAl3qzrbInnfPGYYmoDMldpuMmVEJQst7OInQEGNb+JC/t5IA6flfk+QpQmRa+IjEC3QjiFdoc5y1Vj7qZVlKDk1hleUv9xWBzKpJJk71vV7hpPALx4azgvbiF/4YY7arCR1nNxvPvDdwjY7TEqfzGpg25pgfD0DN7THXyWD2ZeQOzeLcLpHLordgSuM5Uki8hIma7Y0JgTd7xfDq3xtephVPerlXk9RY2XJYsd2VAf0mfhalsrtWzfmbylp5fhIMKY8ZqHe2C1bjgoAX/+6NfNaIQvn3m1xmVN/nd3VEsXDyg/QDqo8ftFdvswK+NaX44nBBjNyfMcTRrZAEHBXq9aSDME9CxPY8VveLLQxBIUVw7bjZrM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
