travis:
  secure:
    BINSTAR_TOKEN: DlIuIfvBOA7ttmQE1rG1BCxTHu+uae1Y2L17rGjvxWzu+oR08+yrl7U1zjMuS8vwq8/8Xzpl0yalIo00ja0Gg2Q0MH7ITck0pMjP7mhx7edih2jmiLrU7Eayn+abJ6ZL2yTaqDL57ZT1J4U2zB81/M44qniPk0M30hUXmLpmOQplNSmV4dZbxahbi+k6oP9zNvwdJDTpbCJPrkxGOqR2W+PFsmi7IDHpv+wRU0aA5ZaWj+fMulfSVVIlI5y5D9T0e79kgfKq1paYknrBsiUbOKparlVMpjP3l5XQSshNufbM5XaOV5MHNTOGCGmPL491Ks/aisDgfOdGkixPuEQMy9otS0coLSHwfxArSajtqul2+k9MMDGSD88K9NwaDdQYL7LZLLWugJvwwLjIrjizsRBPRwEdr45o6YxE35KMV5NYQawVca9snfEaK4yozeWXYT1P0yXsq/rjNhWN1NEvDwi3GbaMJ5LW5oLalbjc3BH+w+kbigInacpr0T1XEBIKq7kvXB+7Q7G1WrVxF8j4J79PIajw9Uwtsn2vU3Trz1JD7rus0ubFlCs5ktPkNwrg7GEUlJb76kR2fP4p8Eu2EI+RGews3qOLhgad/VsEepfIGo4W5nNfa05I74ZulzXnTtUpQkX69v6h8gfrGq4WIq/pNrbmUIOawVOi3fOx3HQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
