travis:
  secure:
    BINSTAR_TOKEN: CRNJf2PzNC142hnwS7tHNU2kFO+3JjCKm5oUAJ+d79PLGRvcfSDmXbwqwf9e87h1B0cx4grlaoy0dXk7geS9F+sOCCyVsIu84ujH6rEMrl7bN6uss/i/DzxZXE1Xsnb+9fJ/I8eym+tK31eQFrijJMnglWP+dzzmoOAW9UI1H/iGpDxZdHsDKfpJp9/9btUNfy9BjXl5FNV/YWS6rgJ9DsYDkIAbXYLHUy/+xLsKayn3wqhu1J3gFQsgcJjn/NEavjJOFXnX+3mnNx2nZz6o/UTSsHZaeOlAVsZfQfq0AkvDNWObuLYzQIo8JBPW58+gDK++s+X73kWoAe9d2/3VRPZF/B93auwj+f9oKuf7aR1UfCD1VXivG0UtoIrvQsRr0WtygggfeZ0ocPYBtHxbiB3a8jtvox9jp7Ks6FkTKs6LcOsHLHvBGuPWokC2fQmW33azq07M/AL9kd1LmxaIJa3/pl9cYpSox70AVzKVj8meKB5PgzlbMMAp1aF6mEoFq/2lT9jhoc1R6h3p6INXsHVTsP/sV8dWDM9ISAQU2CvturQOA+yabLdcaNPey8+UWWbowfCc9KUTofvKZcNwjIX7A0JYsCODdryrsz6NoQVkhcpifRzw+XODz2a1wli143BI/O27lvSH8LZJqiHgNPn5ubTXxi5kxPZ/Frvz2Ig=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
