travis:
  secure:
    BINSTAR_TOKEN: NeaBhuE3oSaXQU216GZsi+zPs25g1+ydW7WhqPCj3u9nCsLTyfD51vF+0pQg0SsUfyHI7j/aoa/bnrN/xTQn7E+sKMUEQpucmGbPW82lhn2PhV65Q4tgLd4AiXgE92RVRd0TzR6oYZde/PLTcqsJDIm24UFSY/nNMGUjKjx9sJFw+YIDvuwlXywJtPynol4yBvpjhrkbSsoMh8LTJOw4EsB0ghXX/BQD7SR4CEicWJEsNZE4/DCFbxtKAi2DHVT+tUpE2Rsl09UOM6qmqPz86+nWEnhN2YfosFAMLeVmQEHCFtsRBcOr2fxLzAl3qzrbInnfPGYYmoDMldpuMmVEJQst7OInQEGNb+JC/t5IA6flfk+QpQmRa+IjEC3QjiFdoc5y1Vj7qZVlKDk1hleUv9xWBzKpJJk71vV7hpPALx4azgvbiF/4YY7arCR1nNxvPvDdwjY7TEqfzGpg25pgfD0DN7THXyWD2ZeQOzeLcLpHLordgSuM5Uki8hIma7Y0JgTd7xfDq3xtephVPerlXk9RY2XJYsd2VAf0mfhalsrtWzfmbylp5fhIMKY8ZqHe2C1bjgoAX/+6NfNaIQvn3m1xmVN/nd3VEsXDyg/QDqo8ftFdvswK+NaX44nBBjNyfMcTRrZAEHBXq9aSDME9CxPY8VveLLQxBIUVw7bjZrM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
